-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-11-12 10:02:25 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE draft (
    draftyear     INTEGER,
    draftposition INTEGER,
    draftround INTEGER,
    playerid INTEGER,
    teamid INTEGER
);

ALTER TABLE draft ADD CONSTRAINT draft_pk PRIMARY KEY ( draftyear, draftposition,  draftround);


CREATE TABLE game (
    gameid   INTEGER NOT NULL,
    seasonid INTEGER NOT NULL,
    gamedate DATE,
    HomeScore INTEGER,
    AwayScore INTEGER,
    HomeShots INTEGER,
    AwayShots INTEGER,
    HomeTeam INTEGER, 
    AwayTeam INTEGER,
    Venue VARCHAR(30),
    WinningGoalieId INTEGER
);

ALTER TABLE game ADD CONSTRAINT game_pk PRIMARY KEY ( gameid, seasonid);

CREATE TABLE gameevent (
    name          VARCHAR2(50 CHAR),
    playid INTEGER,
    game_gameid   INTEGER NOT NULL,
    game_seasonid INTEGER NOT NULL,
    team_teamid   INTEGER NOT NULL,
    player_1 INTEGER NOT NULL,
    player_2 INTEGER,
    player_3 INTEGER,
    goalie INTEGER,
    Reason VARCHAR(30),
    Shottype VARCHAR(30),
    Penmin integer,
    xcoord integer, 
    ycoord integer,
    eventperiod integer,
    timeremaining varchar(5)
);

ALTER TABLE gameevent
    ADD CONSTRAINT gameevent_pk PRIMARY KEY ( playid, game_gameid, game_seasonid, team_teamid );


CREATE TABLE player (
    fullname       VARCHAR2(50 CHAR),
    player_id      NUMBER NOT NULL,
    draftyear     INTEGER,
    draftposition INTEGER,
    draftround INTEGER,
    pposition varchar(1)
);

ALTER TABLE player ADD CONSTRAINT player_pk PRIMARY KEY ( player_id );

CREATE TABLE playerteam (
    player_player_id NUMBER NOT NULL,
    team_teamid      INTEGER NOT NULL,
    season_seasonid INTEGER NOT NULL
);

ALTER TABLE playerteam ADD CONSTRAINT playerteam_pk PRIMARY KEY ( player_player_id, team_teamid, season_seasonid);


CREATE TABLE season (
    seasonid INTEGER NOT NULL
);

ALTER TABLE season ADD CONSTRAINT season_pk PRIMARY KEY ( seasonid );

CREATE TABLE team (
    teamid         INTEGER NOT NULL,
    teamname           VARCHAR2(20 CHAR),
    teamlocation       VARCHAR2(20 CHAR)
);

ALTER TABLE team ADD CONSTRAINT team_pk PRIMARY KEY ( teamid );


ALTER TABLE game
    ADD CONSTRAINT game_season_fk FOREIGN KEY ( seasonid )
        REFERENCES season ( seasonid );

ALTER TABLE game
    ADD CONSTRAINT game_hometeam_fk FOREIGN KEY ( HomeTeam )
        REFERENCES team ( teamid );
        
ALTER TABLE game
    ADD CONSTRAINT game_awayeam_fk FOREIGN KEY ( AwayTeam )
        REFERENCES team ( teamid );

ALTER TABLE gameevent
    ADD CONSTRAINT gameevent_game_fk FOREIGN KEY ( game_gameid, game_seasonid )
        REFERENCES game ( gameid, seasonid );

ALTER TABLE gameevent
    ADD CONSTRAINT gameevent_team_fk FOREIGN KEY ( team_teamid )
        REFERENCES team ( teamid );
        
ALTER TABLE gameevent
    ADD CONSTRAINT gameevent_player1_fk FOREIGN KEY ( player_1 )
        REFERENCES player ( player_id);
        
ALTER TABLE gameevent
    ADD CONSTRAINT gameevent_player2_fk FOREIGN KEY ( player_2 )
        REFERENCES player ( player_id);
        
ALTER TABLE gameevent
    ADD CONSTRAINT gameevent_player3_fk FOREIGN KEY ( player_3 )
        REFERENCES player ( player_id);

ALTER TABLE gameevent
    ADD CONSTRAINT gameevent_goalie_fk FOREIGN KEY ( goalie )
        REFERENCES player ( player_id);

ALTER TABLE player
    ADD CONSTRAINT player_draft_fk FOREIGN KEY ( draftyear, draftposition,  draftround )
        REFERENCES draft ( draftyear, draftposition,  draftround);

ALTER TABLE playerteam
    ADD CONSTRAINT playerteam_player_fk FOREIGN KEY ( player_player_id )
        REFERENCES player ( player_id );

ALTER TABLE playerteam
    ADD CONSTRAINT playerteam_team_fk FOREIGN KEY ( team_teamid )
        REFERENCES team ( teamid );

ALTER TABLE playerteam
    ADD CONSTRAINT playerteam_season_fk FOREIGN KEY ( season_seasonid)
        REFERENCES season ( seasonid);

ALTER TABLE draft
    ADD CONSTRAINT team_draft_fk FOREIGN KEY ( teamid)
        REFERENCES team ( teamid);

ALTER TABLE draft
    ADD CONSTRAINT draft_player_fk FOREIGN KEY ( playerid)
        REFERENCES player ( player_id);


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           2
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          2
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
